CREATE TABLE "zfweb_address" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"add1" varchar(256) NOT NULL,
	"add2" varchar(256) NOT NULL,
	"add3" varchar(256) NOT NULL,
	"city" varchar(1024) NOT NULL,
	"state" varchar(256) NOT NULL,
	"zip" integer NOT NULL,
	"postcode" varchar(256),
	"province" varchar(256),
	"country" varchar(256) NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_cart_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_cart_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_user_id" varchar(256),
	"stripe_customer_id" varchar(256),
	"first_name" varchar(256) NOT NULL,
	"middle_name" varchar(256),
	"last_name" varchar(256) NOT NULL,
	"email" varchar(1024) NOT NULL,
	"phone" varchar(32),
	"is_user" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "zfweb_customer_clerk_user_id_unique" UNIQUE("clerk_user_id"),
	CONSTRAINT "zfweb_customer_stripe_customer_id_unique" UNIQUE("stripe_customer_id")
);
--> statement-breakpoint
CREATE TABLE "zfweb_discount" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_discount_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" varchar(1024) NOT NULL,
	"discount" numeric NOT NULL,
	"free_shipping" boolean NOT NULL,
	"active" boolean DEFAULT false,
	"number_of_uses" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"payment_intent_id" varchar(256) NOT NULL,
	"status" varchar(64) DEFAULT 'pending' NOT NULL,
	"customer_email" varchar(256) NOT NULL,
	"customer_name" varchar(256) NOT NULL,
	"shipping_address" text NOT NULL,
	"products" integer[] NOT NULL,
	"total" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "zfweb_order_payment_intent_id_unique" UNIQUE("payment_intent_id")
);
--> statement-breakpoint
CREATE TABLE "zfweb_order_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_order_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(1024) NOT NULL,
	"description" varchar(4096) NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"img_url" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"img_key" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"inventory" integer NOT NULL,
	"sku" varchar(1024),
	"category_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_product_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_product_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" varchar(1024) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_shopping_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_shopping_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_token" varchar(64) NOT NULL,
	"user_id" integer,
	"total" numeric DEFAULT '0' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "zfweb_shopping_session_session_token_unique" UNIQUE("session_token")
);
--> statement-breakpoint
ALTER TABLE "zfweb_address" ADD CONSTRAINT "zfweb_address_customer_id_zfweb_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_cart_item" ADD CONSTRAINT "zfweb_cart_item_session_id_zfweb_shopping_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."zfweb_shopping_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_cart_item" ADD CONSTRAINT "zfweb_cart_item_product_id_zfweb_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."zfweb_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_order" ADD CONSTRAINT "zfweb_order_user_id_zfweb_customer_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_order_items" ADD CONSTRAINT "zfweb_order_items_order_id_zfweb_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."zfweb_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_order_items" ADD CONSTRAINT "zfweb_order_items_product_id_zfweb_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."zfweb_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD CONSTRAINT "zfweb_product_category_id_zfweb_product_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."zfweb_product_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_shopping_session" ADD CONSTRAINT "zfweb_shopping_session_user_id_zfweb_customer_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."zfweb_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "customer_email_idx" ON "zfweb_customer" USING btree ("email");--> statement-breakpoint
CREATE INDEX "customer_clerk_user_id_idx" ON "zfweb_customer" USING btree ("clerk_user_id");--> statement-breakpoint
CREATE INDEX "title_idx" ON "zfweb_product" USING btree ("title");