CREATE TABLE "zfweb_shipping_rate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_shipping_rate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"zone_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"price_alone" numeric(10, 2) NOT NULL,
	"price_with_others" numeric(10, 2) NOT NULL,
	"delivery_estimate" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_shipping_zone" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_shipping_zone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" varchar(1024),
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zfweb_shipping_zone_country" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zfweb_shipping_zone_country_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"zone_id" integer NOT NULL,
	"country_code" varchar(2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "zfweb_order" ADD COLUMN "is_gift" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_order" ADD COLUMN "is_test" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD COLUMN "img_crop" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD COLUMN "status" varchar(32) DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD COLUMN "sort_order" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD COLUMN "on_sale" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD COLUMN "url_handle" varchar(256);--> statement-breakpoint
ALTER TABLE "zfweb_shipping_rate" ADD CONSTRAINT "zfweb_shipping_rate_zone_id_zfweb_shipping_zone_id_fk" FOREIGN KEY ("zone_id") REFERENCES "public"."zfweb_shipping_zone"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zfweb_shipping_zone_country" ADD CONSTRAINT "zfweb_shipping_zone_country_zone_id_zfweb_shipping_zone_id_fk" FOREIGN KEY ("zone_id") REFERENCES "public"."zfweb_shipping_zone"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "shipping_zone_country_unique" ON "zfweb_shipping_zone_country" USING btree ("country_code");--> statement-breakpoint
CREATE INDEX "url_handle_idx" ON "zfweb_product" USING btree ("url_handle");--> statement-breakpoint
ALTER TABLE "zfweb_product" ADD CONSTRAINT "zfweb_product_url_handle_unique" UNIQUE("url_handle");